import type { Content } from "./en";

/**
 * Spanish copy (Mexican Spanish, `usted`).
 *
 * Typed against `Content`, so a missing or misspelled key fails `tsc` instead
 * of silently rendering English on a Spanish page.
 *
 * Pending review by bilingual staff before launch. `/tuition` and `/policies`
 * are the priority: those are billing terms and licensing disclosures, not
 * marketing copy.
 */
export const es: Content = {
  meta: {
    title: "Capstone Quest Academy",
    description:
      "Capstone Quest Academy — Preescolar aprobado por DES en Tucson y Yuma. Aprendizaje a través del juego para niños de 3 a 5 años. Inscripciones abiertas.",
  },

  common: {
    scheduleTour: "Agende una visita",
    startEnrollment: "Comenzar la inscripción",
    seeRates: "Ver tarifas",
    enroll: "Inscribirse",
    talkWithUs: "Hable con nosotros",
    ourStory: "Nuestra historia",
    backHome: "Volver al inicio",
    hoursLine: "Lunes a viernes, 7:00 a. m. – 6:00 p. m.",
    hoursShort: "7:00 a. m. – 6:00 p. m.",
    formNotice: "Qué pasa con estos datos: se envían por correo a la oficina de la escuela para poder responderle. No los vendemos ni los compartimos. Consulte nuestro",
    formNoticeLink: "aviso de privacidad",
    skipToContent: "Saltar al contenido principal",
    close: "Cerrar",
    logoHome: "Inicio de Capstone Quest Academy",
    opensNewTab: "(se abre en una pestaña nueva)",
    pdf: "PDF",
  },

  pageTitles: {
    home: "Preescolar en Tucson y Yuma",
    about: "Nosotros",
    campuses: "Centros",
    campus: "{campus}",
    careers: "Empleo",
    clever: "Clever y portales estudiantiles",
    contact: "Contacto",
    enroll: "Inscripción",
    faq: "Preguntas frecuentes",
    info: "Información",
    parents: "Recursos para familias",
    handbook: "Manual para padres",
    policies: "Políticas",
    privacy: "Aviso de privacidad",
    programs: "Programas",
    tour: "Agende una visita",
    tuition: "Colegiatura y cuotas",
    whyUs: "Por qué elegirnos",
    accessibility: "Accesibilidad",
    notFound: "Página no encontrada",
  },

  forms: {
    requiredNote: "Los campos marcados con * son obligatorios.",
    required: "Este campo es obligatorio.",
    email: "Escriba un correo electrónico, por ejemplo nombre@ejemplo.com.",
    invalid: "Revise este dato e inténtelo de nuevo.",
  },

  a11yMenu: {
    trigger: "Accesibilidad",
    title: "Accesibilidad",
    description: "Ajuste cómo se ve este sitio. Sus preferencias se guardan en este dispositivo.",
    textSize: "Tamaño del texto",
    sizes: { base: "Normal", lg: "Grande", xl: "Más grande" },
    toggles: {
      contrast: { label: "Más contraste", hint: "Oscurece el texto y refuerza los bordes." },
      links: { label: "Subrayar enlaces", hint: "Marca cada enlace sin depender del color." },
      font: { label: "Letra más sencilla", hint: "Una letra más ancha, con más espacio entre letras y renglones." },
      motion: { label: "Reducir movimiento", hint: "Evita que la página anime elementos al desplazarse." },
    },
    reset: "Restablecer",
    done: "Listo",
    atNote:
      "¿Usa un lector de pantalla, lupa u otra tecnología de asistencia? Funciona directamente con este sitio; no necesita estos ajustes. Si algo le resulta difícil de usar, por favor",
    atNoteLink: "avísenos",
  },

  search: {
    trigger: "Buscar",
    title: "Buscar en Capstone Quest",
    inputLabel: "Buscar en el sitio",
    placeholder: "Centros, programas, empleo…",
    empty: "No hay páginas que coincidan.",
    pages: {
      home: { title: "Inicio", blurb: "Programas preescolares de Capstone Quest Academy en Tucson y Yuma." },
      tucson: { title: "Centro de Tucson", blurb: "1150 North Country Club Road, Tucson · (520) 462-7788" },
      yuma: { title: "Centro de Yuma", blurb: "1220 South 4th Avenue, Yuma · (928) 977-9318" },
      programs: { title: "Programas", blurb: "Un solo salón preescolar de edades mixtas para niños de 3 a 5 años, más cuidado antes y después de clases, de 7 a. m. a 6 p. m." },
      info: { title: "Información", blurb: "Nosotros, programas, recursos para familias y calendarios." },
      clever: { title: "Clever", blurb: "Accesos a Clever, PowerSchool, ClassDojo y RAZ Kids." },
      faq: { title: "Preguntas frecuentes", blurb: "Costo, horarios, edades, DES, comidas, proporciones y visitas, con respuestas claras." },
      tuition: { title: "Colegiatura y cuotas", blurb: "Tarifas semanales de preescolar, cuidado antes y después de clases, descuentos para hermanos y condiciones de pago." },
      policies: { title: "Políticas", blurb: "Inscripción, entrega de niños, disciplina, acceso de los padres e informes de inspección." },
      careers: { title: "Empleo", blurb: "Enseñe preescolar en Tucson o Yuma. Grupos pequeños, prestaciones y un ambiente familiar." },
      about: { title: "Nosotros", blurb: "Preescolar aprobado por DES desde 2013. Pasos pequeños, grandes sueños." },
      parents: { title: "Familias", blurb: "Menús, manuales, DES, colegiatura y colaboración con las familias." },
      whyUs: { title: "Por qué elegirnos", blurb: "Grupos pequeños, seguridad, un plan de estudios que prepara para la escuela, aprobado por DES." },
      enroll: { title: "Inscripción", blurb: "Inscripciones abiertas. Muchas veces se completa en un solo día." },
      tour: { title: "Agende una visita", blurb: "Conozca un salón en Tucson o Yuma una mañana entre semana." },
      handbook: { title: "Manual para padres", blurb: "Admisiones, rutinas diarias, disciplina y la política de prevención de suspensión y expulsión." },
      privacy: { title: "Privacidad", blurb: "Qué recopila este sitio, para qué y quién lo ve." },
      contact: { title: "Contacto", blurb: "(520) 462-7788 · admin@capstonequestacademy.com" },
      accessibility: { title: "Accesibilidad", blurb: "Cómo está hecho este sitio para que todos puedan usarlo, y cómo avisarnos de una barrera." },
    },
  },

  banner: {
    label: "Aviso de inscripción",
    text: "Quedan pocos lugares en Tucson y Yuma",
  },

  campusSwitch: {
    label: "Centro",
    call: "Llamar al centro de {campus}",
  },

  localeSwitch: {
    toEs: "Español",
    toEn: "English",
    label: "Cambiar idioma",
    offer: "Would you prefer to view this site in English?",
    offerAccept: "View in English",
    offerDismiss: "No, gracias",
  },

  nav: {
    home: "Inicio",
    campuses: "Centros",
    allCampuses: "Todos los centros",
    info: "Información",
    infoHome: "Información general",
    // "Nosotros" rather than "Quiénes somos": this is now a top-level nav item,
    // and the longer phrase pushed the Spanish header onto a second line at
    // 1024px.
    about: "Nosotros",
    programs: "Programas",
    parents: "Recursos para familias",
    whyUs: "Por qué elegirnos",
    policies: "Políticas",
    tuition: "Colegiatura",
    tuitionFees: "Colegiatura y cuotas",
    faq: "Preguntas frecuentes",
    careers: "Empleo",
    contact: "Contacto",
    menu: "Menú",
    openMenu: "Abrir el menú",
    mainLabel: "Principal",
  },

  footer: {
    blurb: "Preescolar aprobado por DES en Tucson y Yuma desde 2013.",
    visit: "Visítenos",
    explore: "Explorar",
    talk: "Hable con nosotros",
    follow: "Siga a la escuela",
    followLabel: "{name} — Capstone Quest Academy",
    rights: "Todos los derechos reservados.",
    badges: "Aprobado por DES de Arizona · Con licencia estatal · De 3 a 5 años",
    links: {
      programs: "Programas",
      whyUs: "Por qué elegirnos",
      parents: "Familias",
      about: "Quiénes somos",
      clever: "Clever y portales",
      tuition: "Colegiatura y cuotas",
      policies: "Políticas",
      careers: "Empleo",
      info: "Información",
      tour: "Agende una visita",
      privacy: "Privacidad",
      faq: "Preguntas frecuentes",
      handbook: "Manual para padres",
      accessibility: "Accesibilidad",
    },
  },

  notFound: {
    title: "Página no encontrada",
    text: "Esa página no está en el mapa de Capstone Quest.",
  },

  campuses: {
    tucson: {
      name: "Centro de Tucson",
      blurb:
        "Un centro luminoso y acogedor cerca de midtown, en Tucson: jardines desérticos, áreas de juego con toldos y salones diseñados para niños curiosos de tres a cinco años.",
      feel: "Un hogar fuera de casa, todo el día",
      bannerAlt:
        "El edificio del centro de Tucson, con una manta que dice “Inscripciones abiertas para preescolar — Con licencia, aprobado por DES, día completo, tarifas accesibles” junto al letrero de AmeriSchool Academy.",
      imageAlt:
        "El centro de Tucson: un edificio largo de ladrillo detrás del césped, con una manta que dice “Inscripciones abiertas para preescolar — Con licencia, aprobado por DES, día completo, tarifas accesibles”.",
    },
    yuma: {
      name: "Centro de Yuma",
      blurb:
        "Un centro luminoso y acogedor, de fácil acceso desde cualquier punto de Yuma: jardines desérticos, áreas de juego con toldos y salones diseñados para niños curiosos de tres a cinco años.",
      feel: "Un hogar fuera de casa, todo el día",
      bannerAlt: "",
      imageAlt:
        "El centro de Yuma: un edificio largo de una planta con entrada techada y bancas al frente, un patio cercado a un costado y césped abierto enfrente, bajo un cielo despejado de Arizona.",
    },
  },

  campusPage: {
    eyebrow: "Centro",
    tourTitle: "Lo que verá en su visita",
    tourList: [
      "Salones acogedores donde se saluda a cada niño por su nombre",
      "Área de juego con toldos y talleres al aire libre",
      "Entrada segura y registro de firma al recoger",
      "El mismo plan de estudios aprobado por DES en ambos centros",
    ],
    openInMaps: "Abrir en Maps",
    preferOther: "¿Prefiere el otro centro?",
    compare: "Comparar ubicaciones",
    staffTitle: "Conozca al equipo de {campus}",
    staffLede: "Las maestras que su hijo verá cada mañana, en sus propias palabras.",
  },

  programs: {
    "pre-k": {
      name: "Preescolar",
      ages: "De 3 a 5 años",
      hours: "Día completo, 3 o 5 días",
      imageAlt: "Dos niños mirando con binoculares de juguete en su salón",
      summary:
        "Un solo salón de edades mixtas donde niños de tres, cuatro y cinco años aprenden juntos: comparten, se expresan y exploran por medio del juego, y salen listos para el kínder.",
      points: [
        "Centros de juego y tiempo al aire libre todos los días",
        "Prelectura, matemáticas iniciales y curiosidad científica",
        "Lenguaje y acompañamiento socioemocional, con rutinas que hacen que los pequeños se sientan seguros",
        "Portafolios que acompañan a su hijo al entrar a kínder",
      ],
    },
    "extended-day": {
      name: "Cuidado antes y después de clases",
      ages: "De 3 a 5 años",
      hours: "7:00–8:00 a. m. · 3:30–6:00 p. m.",
      imageAlt: "Una niña haciendo burbujas al aire libre, con una compañera detrás",
      summary:
        "Cuidado complementario con costo adicional, usado por familias trabajadoras desde 2013: llegada temprana y salida tardía con los mismos maestros de confianza.",
      points: [
        "Llegada temprana de 7:00 a 8:00 a. m.",
        "Salida tardía de 3:30 a 6:00 p. m., de lunes a viernes",
        "Refrigerio, descanso y juego al aire libre después de la jornada académica",
      ],
    },
  },

  documents: {
    handbook: {
      title: "Manual para padres",
      blurb:
        "El manual completo del preescolar Capstone Quest (PDF): admisiones, colegiatura, horario diario, disciplina y la política de prevención de suspensión y expulsión.",
    },
    fees: {
      title: "Tarifas de preescolar",
      blurb: "Tarifas de los programas, condiciones de pago y el acuerdo de tarifas que firman las familias. Vigente desde el 1 de agosto de 2024.",
    },
    "parent-rights": {
      title: "Manual de derechos de los padres",
      blurb: "Derechos de los padres en escuelas chárter públicas de Arizona (ADE).",
    },
    "student-handbook": {
      title: "Manual del estudiante",
      blurb: "Manual que se comparte con las familias de AmeriSchools Academy.",
    },
    wellness: {
      title: "Política de bienestar",
      blurb: "Normas de nutrición, actividad física y bienestar.",
    },
    breakfast: {
      title: "Menú de desayuno de Tucson",
      blurb: "Desayunos que se ofrecen actualmente en el centro de Tucson.",
    },
    lunch: {
      title: "Menú de almuerzo de Tucson",
      blurb: "Almuerzos que se ofrecen actualmente en el centro de Tucson.",
    },
    supplies: {
      title: "Lista de útiles escolares",
      blurb: "Lo que debe traer para el primer día.",
    },
  },
  hero: {
    /** Names the homepage h1, whose letters are decorative spans. */
    wordmark: "Capstone Quest Academy",
    eyebrow: "Programas preescolares en",
    // Kept to roughly the English length so it sits on one line in the hero's
    // 32rem column; the gold rule under it spans the sentence, and a line that
    // wraps leaves the rule running past the end of the text.
    tagline: "Donde la curiosidad crece y el futuro brilla.",
    lede: "Un ambiente de aprendizaje afectuoso y basado en el juego que ayuda a su hijo a desarrollar confianza, amistades y las bases para toda la vida.",
    imageAlt: "Una niña de preescolar coloreando en una mesa del salón",
    watchVideo: "Ver nuestro video",
    videoTitle: "Una mañana en Capstone Quest",
    whyTitle: "Por qué nos eligen las familias",
    reasons: {
      smallClasses: { title: "Grupos pequeños", text: "Atención personalizada para cada niño." },
      safe: { title: "Seguridad y protección", text: "Máxima seguridad con cuidado de confianza." },
      schoolReady: { title: "Listos para la escuela", text: "Un plan de estudios preescolar que desarrolla habilidades y confianza." },
      family: { title: "Alianza con la familia", text: "Trabajamos con usted en cada paso del camino." },
    },
    qualityFirst: {
      title: "Programa Quality First",
      text: "Programa participante de Quality First de Arizona.",
    },
    badges: {
      ages: "De 3 a 5 años",
      teachers: "Maestros afectuosos y con experiencia",
      play: "Aprendizaje por medio del juego",
      locations: "Ubicaciones en Tucson y Yuma",
      des: "100% aprobado por DES",
    },
  },
  parents: {
    eyebrow: "Familias",
    title: "Usted forma parte del equipo",
    lede: "Manuales, menús y los mismos recursos para familias que están en la sección de Información.",
    resources: {
      handbook: { title: "Manual para padres", text: "Admisiones, rutinas diarias, disciplina y la política de prevención de suspensión y expulsión.", cta: "Leer el manual" },
      tours: { title: "Visitas y calendario", text: "Recorra los salones, conozca a los maestros y observe una reunión matutina real.", cta: "Agende una visita" },
      packet: { title: "Paquete de inscripción", text: "Formularios de salud, contactos de emergencia y documentación de DES en una sola cita.", cta: "Comenzar la inscripción" },
      policies: { title: "Políticas", text: "Inscripción, entrega de niños, disciplina y acceso de los padres, tal como están publicadas en ambos centros.", cta: "Leer las políticas" },
      partnership: { title: "Alianza con la familia", text: "Conferencias dos veces al año, mañanas de puertas abiertas y maestros que le devuelven la llamada.", cta: "Hable con nosotros" },
    },
    docsTitle: "Manuales, menús y formularios",
    docsLede: "Los mismos documentos que las familias descargan de la sección de Información de AmeriSchools: derechos de los padres, bienestar, menús y útiles.",
    tuitionTitle: "Colegiatura y DES",
    tuitionText: "El preescolar de día completo cuesta $130.00 por semana con cinco días y $120.00 con tres, y el cuidado antes y después de clases desde $15.00. Hay un 10% de descuento para un hermano adicional. Estamos 100% aprobados por el Departamento de Seguridad Económica de Arizona, y las familias que usan el subsidio de cuidado infantil de DES se inscriben de la misma manera: aplican copagos y le ayudamos con los trámites.",
    tuitionCta: "Ver la lista completa de cuotas",
    tuitionAsk: "Preguntar sobre la colegiatura",
    faqTitle: "Preguntas frecuentes",
  },
  programsPage: {
    eyebrow: "Programas",
    title: "Preescolar diseñado para niños de 3 a 5 años",
    lede: "Primero el juego, y las habilidades justo detrás. Cada programa está aprobado por DES y lo imparten maestros que acompañan a su hijo durante todo el año.",
  },

  campusesPage: {
    eyebrow: "Centros",
    title: "Tucson y Yuma",
    lede: "Dos centros acogedores y con licencia. Un mismo preescolar basado en el juego. Visite el más cercano a su casa, o los dos.",
    details: "Detalles del centro",
    exteriorAlt: "fachada",
    bookTour: "Reserve una visita",
  },
  infoPage: {
    eyebrow: "Información",
    title: "La escuela, en un solo lugar",
    lede: "Todo lo que antes estaba en la sección de Información: quiénes somos, programas, recursos para familias y portales, reescrito para familias de preescolar.",
    cards: {
      about: { title: "Sobre Capstone Quest", text: "Preescolar aprobado por DES en Tucson y Yuma desde 2013. Pequeños pasos, grandes sueños.", cta: "Nuestra historia" },
      programs: { title: "Programas", text: "Un solo salón preescolar de edades mixtas para niños de 3 a 5 años, más cuidado antes y después de clases, de 7 a. m. a 6 p. m.", cta: "Ver programas" },
      parents: { title: "Recursos para familias", text: "Manuales, menús, derechos de los padres, política de bienestar y útiles.", cta: "Para las familias" },
      clever: { title: "Clever y portales", text: "Clever, PowerSchool, ClassDojo y RAZ Kids: los accesos que las familias ya usan.", cta: "Abrir portales" },
      tour: { title: "Agende una visita", text: "Observe una reunión matutina real. La mayoría de las visitas dura unos 40 minutos.", cta: "Reserve una visita" },
      tuition: { title: "Colegiatura y cuotas", text: "Tarifas semanales, cuidado antes y después de clases, descuentos por hermanos y condiciones de pago.", cta: "Ver colegiatura" },
      policies: { title: "Políticas", text: "Inscripción, admisión y entrega de niños, disciplina, acceso de los padres e informes de inspección.", cta: "Leer las políticas" },
      whyUs: { title: "Por qué se quedan las familias", text: "Grupos pequeños, juego que prepara para la escuela y un día que se siente como infancia.", cta: "Por qué elegirnos" },
    },
  },
  cleverPage: {
    eyebrow: "Clever",
    title: "Portales que las familias ya conocen",
    lede: "El sitio actual de AmeriSchools envía “See how my child is doing” a PowerSchool y coloca Clever en la barra superior. Esos enlaces siguen funcionando.",
    portals: {
      clever: "El inicio de sesión único que usa el sitio actual de AmeriSchools para alumnos y personal.",
      powerschool: "Asistencia, calificaciones de hermanos de K a 8 y el enlace histórico “See how my child is doing”.",
      classdojo: "Historias del salón y mensajes del maestro titular.",
      raz: "Lecturas por nivel para los niños que ya están listos para leer en casa.",
      khan: "Práctica opcional; nunca tarea para niños de tres años.",
    },
  },
  aboutPage: {
    eyebrow: "Quiénes somos",
    title: "Una aventura para niños curiosos",
    lede: "Bienvenido a Capstone Quest Academy, donde los pequeños pasos hacen realidad los grandes sueños. Desde 2013, nuestros centros de Tucson y Yuma han sido un hogar fuera de casa: un preescolar certificado por DES que prepara a niños de tres a cinco años para el kínder sin apresurar la infancia.",
    hours: "La jornada académica es de cinco días a la semana. La llegada temprana (7:00–8:00 a. m.) y la salida tardía (3:30–6:00 p. m.) se ofrecen como servicio con costo adicional, para que las familias trabajadoras aprovechen todo el horario de 7 a. m. a 6 p. m.",
    imageAlt: "Seis niños de preescolar con sombreros de pavo de papel, abrazados, posando en su salón.",
    believeTitle: "En qué creemos",
    believe1: "Los niños aprenden haciendo, conversando y sintiéndose parte del grupo. Nuestros maestros diseñan talleres de arte, bloques, cuentos y ciencia al aire libre, donde la lectoescritura y las matemáticas aparecen como herramientas, no como ejercicios. Las familias son aliadas, no visitantes.",
    believe2: "Owl-livia, nuestra mascota con birrete, representa la sabiduría que se gana con calma: intentar, observar, intentar de nuevo.",
    peopleTitle: "Personas que conocen a su hijo",
    meetUs: "Conózcanos en una visita",
    staff: {
      zoe: {
        role: "Maestra",
        campus: "Tucson",
        bio: [
          "¡Hola! Me llamo Miss Zoe Cordova y me emociona mucho ser su maestra este año. Me encanta crear un salón donde los estudiantes se sientan bienvenidos, apoyados y con ganas de aprender.",
          "Algunas de mis cosas favoritas son los colores del atardecer, la barbacoa coreana, los cenzontles, Too Many Carrots y El laberinto del fauno. Me encanta viajar, ir al cine, cocinar, ver atardeceres y pasar tiempo con mis amigos y mi familia. Mis estaciones favoritas son el otoño y el invierno, y siempre me hace feliz cualquier cosa picante.",
          "¡Espero un año lleno de aprendizaje, risas, amabilidad y muchos recuerdos maravillosos juntos!",
        ],
      },
      juridia: {
        role: "Asistente de maestra",
        campus: "Tucson",
        bio: [
          "¡Hola! Me llamo Juridia Hernandez, pero pueden decirme Miss J. Me emociona mucho ser su asistente de maestra y ayudar a que nuestro salón sea un lugar divertido, acogedor y alentador para cada estudiante.",
          "Algunas de mis cosas favoritas son el naranja y el rosa, la comida china, las nutrias marinas, el voleibol, el K-pop y el R&B, y el invierno. También me encanta hacer uñas, cocinar y hornear para los demás, bailar, maquillarme, decorar para Navidad y pasar tiempo con mi familia y mis amigos. Dos lugares que quiero mucho son Corea y Japón.",
          "¡Espero ayudar a nuestros estudiantes a aprender, reír, crecer y tener un año increíble juntos! 💕🌈",
        ],
      },
      sidney: {
        role: "Maestra de preescolar",
        campus: "Yuma",
        bio: [
          "Soy una maestra de preescolar cariñosa, apasionada por ayudar a los niños pequeños a aprender, crecer y sentirse seguros de sí mismos.",
          "Cuando no estoy en el salón, disfruto pasar tiempo con mis animales, explorar la naturaleza y perderme en un buen libro.",
          "Cada día les traigo a mis estudiantes curiosidad, amabilidad y amor por el aprendizaje. Llevo 3 años en Capstone.",
        ],
      },
      tianna: {
        role: "Maestra de preescolar",
        campus: "Yuma",
        bio: [
          "¡Hola a todos! Soy Ms. Tianna, tengo 28 años y llevo 5 años enseñando con mucho cariño aquí en el preescolar Capstone.",
          "Cuando no estoy en el salón, me encanta viajar y pasar tiempo con mi familia.",
        ],
      },
    },
  },
  schedule: {
    s1: "Bienvenida, centros de la mañana y asistencia",
    s2: "Hora del círculo, lectura en voz alta y baile",
    s3: "Juego al aire libre",
    s4: "Arte, centros y proyectos especiales",
    s5: "Recoger, baño y lavado de manos",
    s6: "Almuerzo",
    s7: "Lectura en parejas",
    s8: "Baño y lavado de manos",
    s9: "Hora de la siesta",
    s10: "Despertar y recoger",
    s11: "Refrigerio",
    s12: "Baile y ejercicio",
    s13: "Juego al aire libre y salida",
  },

  faqs: {
    ages: { q: "¿Qué edades atienden?", a: "Niños de 3 a 5 años, juntos en un mismo salón. La mayoría de las familias comienza el año en que su hijo cumple tres y se queda hasta el año en que está listo para el kínder." },
    des: { q: "¿Están aprobados por DES?", a: "Sí. Ambos centros están 100% aprobados por el Departamento de Seguridad Económica de Arizona y cuentan con licencia estatal. Aceptamos con gusto los subsidios de cuidado infantil de DES." },
    enroll: { q: "¿Qué tan rápido podemos inscribirnos?", a: "Una vez que hacemos la visita y recibimos el paquete completo, muchas familias terminan la inscripción en un solo día, sobre todo cuando hay un lugar disponible para el periodo actual." },
    day: { q: "¿Cómo es un día típico?", a: "Reunión matutina, juego al aire libre, talleres de lectoescritura y matemáticas, almuerzo, descanso, talleres (arte, bloques, ciencia) y círculo de cierre. Los niños de día completo se quedan para el refrigerio y los centros de la tarde." },
    ratio: { q: "¿Cuál es la proporción de maestros por niño?", a: "Cada salón de preescolar tiene un maestro titular y un asistente, y contamos con el personal que exigen las normas de licencia de Arizona, de modo que los grupos son lo bastante pequeños para que se conozca a cada niño por su nombre. El tamaño de los grupos varía un poco según el centro y la edad; pregúntenos las cifras actuales en su visita." },
    checkin: { q: "¿Puedo saber cómo está mi hijo durante el día?", a: "Sí. Llámenos cuando quiera y con gusto revisamos cómo está su hijo. Si lo desea, pida a la maestra de su hijo que le tome fotos o videos cortos durante el día y se los envíe." },
    hours: { q: "¿Cuál es su horario?", a: "El programa académico de preescolar es de cinco días a la semana. Los centros abren de lunes a viernes, de 7:00 a. m. a 6:00 p. m., con llegada temprana (7:00–8:00 a. m.) y salida tardía (3:30–6:00 p. m.) con costo adicional." },
  },

  testimonials: {
    priya: { quote: "Maya entró al kínder feliz y ya sabía esperar su turno, escribir su nombre y hacer buenas preguntas. Capstone Quest hizo que se viera fácil.", role: "Madre de Tucson" },
    marcus: { quote: "Los maestros de verdad conocen a mi hijo. No solo sus alergias: también su camión favorito, lo despacio que agarra confianza y las canciones que lo calman.", role: "Padre de Yuma" },
    danielle: { quote: "Usamos un vale de DES y nunca nos sentimos una familia de segunda. El programa es la misma hermosa experiencia para cada niño del salón.", role: "Madre de Tucson" },
  },

  whyUsPage: {
    eyebrow: "Por qué elegirnos",
    title: "El preescolar con el que se quedan las familias de Arizona",
    lede: "Desde 2013 hemos sido el hogar fuera de casa certificado por DES en Tucson y Yuma: accesible a propósito, excelente a propósito.",
    pillars: {
      small: { title: "Pequeños por diseño", text: "Salones lo bastante pequeños para que se conozca a su hijo, no solo para controlarlo. Los maestros escriben notas de verdad, no plantillas." },
      safety: { title: "Seguridad que se siente", text: "Entradas seguras, recogida con firma, personal capacitado y una cultura de calma. Estamos 100% aprobados por DES y con licencia estatal." },
      ready: { title: "Listos para la escuela, sin dejar de jugar", text: "La lectoescritura, las matemáticas y la autonomía viven dentro de los talleres y los cuentos; nunca hojas de ejercicios para niños de tres años." },
      family: { title: "Alianza con la familia", text: "Visitas, conferencias y maestros que devuelven la llamada, para que nunca tenga que preguntarse cómo estuvo el día." },
    },
    playgroundAlt: "Una niña de preescolar sonríe asomada por la parte alta de un juego infantil azul y rojo.",
    desTitle: "Aprobados por DES. Hechos para las familias.",
    desText: "Ambos centros están totalmente aprobados por el Departamento de Seguridad Económica de Arizona. Aceptamos subsidios de cuidado infantil, y cada familia, con vale o con pago particular, recibe el mismo salón, los mismos maestros y el mismo día.",
    dayTitle: "Un día en preescolar",
    wordsTitle: "Las familias en sus propias palabras",
    faqTitle: "Preguntas que escuchamos en cada visita",
  },
  homePage: {
    eyebrow: "Preescolar en Tucson y Yuma",
    title: "Los pequeños pasos hacen realidad los grandes sueños",
    welcome:
      "Bienvenido a Capstone Quest Academy, donde los pequeños pasos hacen realidad los grandes sueños. Somos el preescolar más accesible de las comunidades a las que servimos. Ubicados en los planteles de AmeriSchools, en el corazón de Tucson y Yuma desde 2013, nuestros programas preescolares acompañan a los más pequeños en una aventura de aprendizaje y crecimiento.",
    body: "Los centros son un hogar fuera de casa: juego, descubrimiento y un año de preparación para el kínder sin apresurar la infancia. Las clases son cinco días a la semana. Abrimos de 7:00 a. m. a 6:00 p. m., de lunes a viernes, con cuidado antes y después de clases para familias trabajadoras.",
    pills: [
      "De 3 a 5 años, en Tucson y Yuma desde 2013",
      "Abierto de 7:00 a. m. a 6:00 p. m., de lunes a viernes",
      "Cuidado antes y después de clases en ambos centros",
      "Aprobado por DES · Con licencia del estado de Arizona",
    ],
    programsEyebrow: "Nuestros programas",
    programsTitle: "Un año de preescolar que se sigue sintiendo como infancia",
    seeProgram: "Ver el programa",
    campusesEyebrow: "Dos centros en Arizona",
    campusesTitle: "Cerca de casa en Tucson y Yuma",
    campusesLede: "El mismo plan de estudios basado en el juego, la misma aprobación de DES y grupos pequeños: elija el centro que le quede de paso.",
    visitCampus: "Ver el centro",
    dayEyebrow: "Un día en preescolar",
    dayTitle: "Ritmo, juego y la escuela justa",
    dayNote: "El cuidado antes y después de clases rodea esta jornada, de 7:00 a 8:00 a. m. y de 3:30 a 6:00 p. m.",
    familiesEyebrow: "Nuestras familias",
    familiesTitle: "Listos para el kínder, y siguen siendo ellos mismos",
    ctaTitle: "Inscripciones abiertas",
    ctaNote: "Lugares limitados · Aceptamos DES · Visitas casi todos los días hábiles",
    enrollNow: "Inscríbase ahora",
  },
  /** Etiquetas usadas solo dentro de los datos estructurados. */
  schema: {
    audience: "Niños de 3 a 5 años",
    licence: "Licencia de cuidado infantil de Arizona",
  },

  faqPage: {
    eyebrow: "Preguntas",
    title: "Preguntas frecuentes",
    lede: "Capstone Quest Academy es un preescolar para niños de 3 a 5 años, con centros en Tucson y Yuma, Arizona. Operamos desde 2013. Abajo están las preguntas que más nos hacen las familias, respondidas con claridad.",
    items: {
      cost: {
        q: "¿Cuánto cuesta el preescolar en Capstone Quest Academy?",
        a: "Capstone Quest Academy cobra por semana. El preescolar de cinco días por semana, de 8:00 a. m. a 3:30 p. m., cuesta $130 por semana. Tres días por semana cuesta $120 por semana. El preescolar con cuidado antes y después de clases, de 7:00 a. m. a 6:00 p. m. cinco días por semana, cuesta $160 por semana. No hay cuota de inscripción, ni cuota de materiales, ni depósito. Las tarifas completas del cuidado antes y después de clases están en la página de colegiatura.",
      },
      ages: {
        q: "¿Qué edades acepta Capstone Quest Academy?",
        a: "Capstone Quest Academy atiende a niños de 3 a 5 años en su programa de preescolar. No podemos aceptar niños menores de 3 años. Hay campamentos de verano disponibles para niños de edad escolar, de 6 a 12 años.",
      },
      hours: {
        q: "¿Cuál es el horario de Capstone Quest Academy?",
        a: "Ambos centros abren de lunes a viernes, de 7:00 a. m. a 6:00 p. m. El día de instrucción es de 8:00 a. m. a 3:30 p. m. El cuidado matutino es de 7:00 a 8:00 a. m. y el cuidado vespertino de 3:30 a 6:00 p. m.",
      },
      where: {
        q: "¿Dónde están los centros de Capstone Quest Academy?",
        a: "Capstone Quest Academy tiene dos centros en Arizona. El centro de Tucson está en 1150 North Country Club Road, Tucson, AZ 85716, cerca de Speedway y Country Club, y su teléfono es (520) 462-7788. El centro de Yuma está en 1220 South 4th Avenue, Yuma, AZ 85364, y su teléfono es (928) 977-9318.",
      },
      toilet: {
        q: "¿Mi hijo necesita saber usar el baño para asistir?",
        a: "Sí. Los niños deben usar el baño de forma independiente antes de su primer día en Capstone Quest Academy. Esto significa avisarle a un maestro cuando necesitan ir, manejar su propia ropa y usar ropa interior regular en lugar de pañales o pull-ups. Los accidentes son normales y los manejamos con calma; las familias dejan una muda de ropa en el cubículo de su hijo. Si un niño tiene una discapacidad o condición médica que afecte el uso del baño, la familia debe hablar con el director del centro antes de inscribirlo.",
      },
      des: {
        q: "¿Capstone Quest Academy acepta la asistencia de cuidado infantil de DES?",
        a: "Sí. Capstone Quest Academy está aprobada por el Departamento de Seguridad Económica de Arizona (DES). Las familias solicitan directamente ante DES, no ante la escuela, a través del portal A-to-Z Arizona o llamando al 1-833-947-6396. Por lo general se requiere un ingreso familiar igual o menor al 165 por ciento del Nivel Federal de Pobreza y que el padre o madre trabaje o estudie. Actualmente Arizona tiene una lista de espera para la mayoría de los solicitantes, y el trámite puede tardar hasta 30 días.",
      },
      desStart: {
        q: "¿Mi hijo puede empezar antes de que se apruebe DES?",
        a: "Sí. Una familia puede empezar de inmediato pagando la tarifa semanal completa mientras su solicitud de DES está en trámite. Una vez que DES aprueba a la familia, Capstone Quest Academy reembolsa todos los pagos realizados, de forma retroactiva a la fecha de vigencia de esa aprobación. Las familias no pierden el dinero pagado durante la espera.",
      },
      noDes: {
        q: "¿Qué pasa si no calificamos para DES?",
        a: "Capstone Quest Academy ofrece la Beca Familiar Barr, que cubre hasta el 50 por ciento de las cuotas de preescolar del año en curso. Está dirigida a familias con un niño de 3 a 5 años que no calificaron para DES, o fueron rechazadas, y que de otro modo no pueden obtener servicios de cuidado infantil. Se requiere una solicitud y una revisión de elegibilidad por ingresos. No está dirigida a familias que ya reciben servicios de DES.",
      },
      fees: {
        q: "¿Hay cuotas de inscripción o depósitos?",
        a: "No. Capstone Quest Academy no cobra cuota de inscripción, ni cuota de matrícula, ni cuota de materiales, ni depósito para apartar un lugar. La colegiatura se paga cada lunes. Se aplica un cargo de $10 por pago tardío si no se paga antes del miércoles, y la recogida tardía después de las 6:00 p. m. cuesta $1 por minuto.",
      },
      meals: {
        q: "¿Capstone Quest Academy proporciona comidas?",
        a: "El desayuno y los refrigerios están incluidos en la tarifa semanal. Las familias mandan el almuerzo de su hijo. El campamento de verano para niños mayores incluye desayuno y almuerzo. Las familias informan a la escuela sobre cualquier alergia a alimentos o medicamentos durante la inscripción.",
      },
      ratio: {
        q: "¿Cuál es la proporción de maestros por niño?",
        a: "Capstone Quest Academy mantiene una proporción de un adulto por cada trece niños, tanto en los salones de tres años como en los de cuatro y cinco años. Las licencias de Arizona exigen un adulto por cada trece niños de tres años, uno por cada quince de cuatro años y uno por cada veinte de cinco años, por lo que esta proporción cumple el requisito estatal para los de tres años y lo supera para los de cuatro y cinco.",
      },
      licensed: {
        q: "¿Capstone Quest Academy tiene licencia?",
        a: "Sí. Capstone Quest Academy tiene licencia del estado de Arizona en ambos centros — Tucson con la licencia CDC-17293 y Yuma con la licencia CDC-17301 — y está aprobada por el Departamento de Seguridad Económica de Arizona. Ambos centros participan en Quality First, el programa de mejora de calidad de la educación temprana de Arizona administrado por First Things First. Todo el personal completa una Tarjeta de Autorización de Huellas Digitales de Nivel Uno, una verificación del Registro Central y verificaciones en bases de datos criminales nacionales antes de su primer día.",
      },
      spanish: {
        q: "¿Capstone Quest Academy tiene personal que habla español?",
        a: "Sí. Hay personal que habla español en los centros de Tucson y Yuma de 7:00 a. m. a 6:00 p. m. Las familias pueden hacer la visita, preguntar y hablar con el personal en español en cualquiera de los dos centros, y todo el sitio web está disponible en español.",
      },
      tour: {
        q: "¿Cómo programo una visita?",
        a: "Las visitas son de lunes a viernes, entre las 9:00 a. m. y las 3:30 p. m. en ambos centros, y duran unos 30 minutos. Capstone Quest Academy pide al menos 24 horas de anticipación. Los niños son bienvenidos y los animamos a acompañarlos. Solicite un horario en la página de visitas o llame directamente al plantel.",
      },
      summer: {
        q: "¿Capstone Quest Academy abre durante el verano?",
        a: "Sí. El programa de preescolar para niños de 3 a 5 años funciona todo el año con las mismas tarifas semanales, el mismo programa y las mismas comidas. Capstone Quest Academy también ofrece campamentos de verano por separado para niños de edad escolar, de 6 a 12 años.",
      },
      discounts: {
        q: "¿Capstone Quest Academy ofrece descuentos?",
        a: "Sí. Las familias que inscriben a más de un niño reciben un descuento del 10 por ciento por un hermano adicional, aplicable tanto al preescolar como al cuidado antes y después de clases. El personal de Capstone Quest Academy recibe un descuento del 50 por ciento. No hay descuento por pagar por mes o por año por adelantado.",
      },
      amerischools: {
        q: "¿Capstone Quest Academy forma parte de AmeriSchools Academy?",
        a: "No. Capstone Quest Academy es un negocio independiente y de propiedad privada, y no es una división, plantel ni programa de AmeriSchools Academy. Capstone Quest Academy ha estado alojada en instalaciones de AmeriSchools Academy desde 2013, y ambas organizaciones comparten un edificio y el compromiso de cuidar y enseñar a los niños, pero son entidades separadas. Una familia que se inscribe en Capstone Quest Academy se inscribe con Capstone Quest Academy.",
      },
    },
  },

  tuitionPage: {
    eyebrow: "Colegiatura",
    title: "Preescolar de día completo, con tarifa semanal",
    lede: "Una sola tarifa semanal cubre la jornada académica, de 8:00 a. m. a 3:30 p. m. Agregue el cuidado antes y después de clases si su jornada laboral empieza antes o termina más tarde. Las familias que usan el subsidio de cuidado infantil de DES se inscriben igual; aplican copagos.",
    programsTitle: "Programas de preescolar",
    programsNote: "Elija un programa por niño. Las tarifas son por niño, por semana.",
    perWeek: "por semana",
    programs: {
      p1: { name: "Programa n.º 1", schedule: "5 días a la semana", hours: "8:00 a. m. – 3:30 p. m." },
      p2: { name: "Programa n.º 2", schedule: "3 días a la semana", hours: "8:00 a. m. – 3:30 p. m." },
      bundle: { name: "Preescolar + cuidado antes y después", schedule: "5 días a la semana", hours: "7:00 a. m. – 6:00 p. m.", highlight: "Ahorra 20% frente a contratar ambos por separado" },
    },
    baTitle: "Cuidado antes y después de clases",
    baNote: "De 7:00 a 8:00 a. m. y de 3:30 a 6:00 p. m. Se cobra por separado o incluido en la tarifa de 5 días de arriba.",
    baGroups: { d5: "5 días a la semana", d3: "3 días a la semana" },
    baOptions: { both: "Cuidado antes y después", before: "Solo antes de clases", after: "Solo después de clases" },
    discountsTitle: "Descuentos",
    discounts: [
      "10% de descuento para un hermano adicional, tanto en preescolar como en el cuidado antes y después de clases.",
      "Quienes reciben DES eligen un programa de la misma manera; aplican copagos.",
    ],
    includedTitle: "Qué incluye la cuota",
    included: [
      "Un refrigerio nutritivo por la tarde está incluido en la cuota.",
      "Los padres envían el almuerzo de su hijo cada día de asistencia.",
      "El cuidado de la tarde incluye tiempo de tarea y actividades organizadas, como recreación y juegos, con refrigerio.",
    ],
    termsTitle: "Facturación y condiciones del contrato",
    terms: [
      "Las cuotas se basan en el horario de su contrato, no en la asistencia.",
      "No se cobran los recesos del calendario escolar (si no abrimos) ni los días festivos principales.",
      "Las cuotas se facturan cada lunes y se pagan esa misma noche, por la semana siguiente. El miércoles por la mañana se aplica un recargo de $10.00 por pago tardío.",
      "La recogida tardía cuesta $1.00 por minuto y se cobra en el siguiente ciclo.",
      "La entrega de emergencia para el cuidado antes y después de clases cuesta $15.00, se paga al recoger y debe autorizarla la oficina para confirmar que hay lugar.",
      "Los días adicionales a su contrato se cobran como visitas sueltas. Firmar un contrato nuevo evita esa tarifa.",
      "Debe haber un contrato firmado y documentos de inscripción vigentes en el archivo antes de que su hijo asista.",
    ],
    scholarship: {
      title: "Beca Barr Family Early Learners",
      origin:
        "El fondo fue creado en 2023 por la familia Barr, fundadores de AmeriSchools Academy y de Capstone Quest Academy. Vieron familias trabajadoras de Tucson y Yuma cuyos ingresos superaban el límite de DES y que aun así no podían pagar una educación temprana de calidad y trabajar al mismo tiempo. Las becas se otorgan según la necesidad y se revisan cada año.",
      covers: "Cubre hasta el 50% del costo del preescolar.",
      whoTitle: "Para quién es",
      who: [
        "Familias con un niño de 3 a 5 años que necesitan cuidado y educación temprana.",
        "Familias que solicitaron DES y no calificaron, o a quienes se les negó.",
        "No es para familias que ya reciben DES. Si su solicitud de DES sigue en trámite, el formulario le indica con quién comunicarse.",
      ],
      howTitle: "Cómo solicitarla",
      how: [
        "Descargue y llene la solicitud.",
        "Adjunte sus dos comprobantes de ingresos más recientes: talones de pago, declaraciones de impuestos, estados de cuenta, cartas de beneficios o similares. Sin comprobante de ingresos, su solicitud se retrasa.",
        "Entréguela en su centro.",
      ],
      decision:
        "Las solicitudes se revisan según la necesidad de la familia y sus ingresos, por orden de llegada, y se deciden dentro de los 10 días siguientes a recibir la solicitud completa con los documentos financieros. La beca depende de la verificación de ingresos y de que haya fondos disponibles, y llega hasta el 30 de junio de 2027 mientras su cuenta esté al corriente. Avísenos si sus ingresos cambian o si llega a calificar para DES.",
      cta: "Descargar la solicitud de beca",
    },
    ctaTitle: "¿Listo para inscribirse?",
    ctaText: "Llene un formulario de inscripción por niño y entréguelo en la oficina de registro del centro. Le ayudamos con los trámites de DES si usa un subsidio.",
    feeScheduleCta: "Descargar la lista de tarifas",
    effectiveNote: "Las tarifas mostradas provienen de la lista de cuotas vigente desde el 1 de agosto de 2024. Confirme las tarifas actuales con su centro antes de firmar: llame al {phone} o escriba a",
  },
  policiesPage: {
    handbookLink: "Lea la política completa de prevención en el manual para padres",
    eyebrow: "Políticas",
    title: "Políticas de inscripción, entrega y cuidado",
    lede: "Las políticas de licencia publicadas en ambos centros, con las mismas palabras. Pida en la oficina cualquiera de estos documentos impresos.",
    questionsTitle: "¿Tiene preguntas sobre alguna de estas políticas?",
    questionsText: "Llame al {phone} o pase por la oficina. Las políticas de suspensión y expulsión están disponibles para los padres que las soliciten, y los informes de inspección de licencia pueden consultarse en el centro.",
    items: {
      enrollment: {
        title: "Procedimientos de inscripción del niño",
        body: "Los niños quedan inscritos una vez completada toda la documentación de inscripción requerida, que incluye, entre otros:",
        list: ["Solicitud de inscripción", "Datos de contacto de emergencia", "Registro de vacunas", "Expedientes de salud exigidos por las normas de licencia"],
        footer: "La inscripción depende de la disponibilidad y de que la edad del niño sea adecuada para el programa de preescolar.",
      },
      release: { title: "Procedimientos de admisión y entrega del niño", body: "Los niños se entregan únicamente a los padres o a las personas autorizadas por escrito por el padre, la madre o el tutor. Se exige identificación cuando se entrega a un niño a una persona que el personal no conoce. Los niños no pueden salir del centro sin supervisión autorizada.", list: [], footer: "" },
      discipline: { title: "Lineamientos de disciplina", body: "El centro usa técnicas de orientación positivas y apropiadas para la edad, consistentes y adecuadas al desarrollo de los niños de preescolar. La disciplina se centra en la redirección, en modelar la conducta adecuada y en establecer expectativas claras. Nunca se usa el castigo corporal, la humillación ni el lenguaje abusivo.", list: [], footer: "" },
      disenrollment: { title: "Procedimientos de baja del niño", body: "El padre, la madre o el tutor pueden dar de baja al niño mediante aviso por escrito al centro. El centro se reserva el derecho de dar de baja a un niño por motivos que incluyen, entre otros, la falta de pago de cuotas, el incumplimiento de las políticas del centro o preocupaciones de seguridad, conforme a las normas de licencia y a las políticas del centro.", list: [], footer: "" },
      suspension: { title: "Política de suspensión y expulsión", body: "El centro cuenta con políticas escritas sobre suspensión y expulsión que incluyen estrategias de prevención, expectativas claras y métodos de orientación apropiados para la edad. Estas políticas están disponibles para los padres que las soliciten.", list: [], footer: "" },
      access: { title: "Acceso de los padres", body: "Los padres tienen acceso a las áreas del centro donde su hijo inscrito recibe cuidado infantil durante el horario normal de operación.", list: [], footer: "" },
      pesticide: { title: "Aviso de aplicación de plaguicidas", body: "Se avisa a los padres con al menos 48 horas de anticipación antes de aplicar plaguicidas en las instalaciones del centro, conforme a los requisitos estatales.", list: [], footer: "" },
      inspection: { title: "Informes de inspección", body: "Se informa a los padres que los informes de inspección de licencia están disponibles para su consulta en el centro.", list: [], footer: "" },
    },
  },
  careersPage: {
    eyebrow: "Empleo",
    title: "Venga a enseñar el año que más importa",
    lede: "Capstone Quest contrata a personas que disfrutan los grupos pequeños, el juego de verdad y a las familias que quieren ser aliadas. Se requiere autorización de huellas digitales. Para los puestos de maestro titular se espera título universitario y AEPA o NES.",
    perks: {
      classes: { title: "Grupos pequeños", text: "Enseñe a un grupo, no a una multitud. De verdad conocerá a cada niño y a cada familia." },
      benefits: { title: "Prestaciones reales", text: "Seguro médico, aportaciones para el retiro, reembolso de colegiatura e incentivos de ingreso adicional." },
      invent: { title: "Espacio para crear", text: "Talleres, juego al aire libre y un plan de estudios que todavía deja ser creativos a los maestros." },
      family: { title: "Un equipo pequeño", text: "Centros preescolares en Tucson y Yuma con la misma cultura tranquila y aprobada por DES." },
    },
    openTitle: "Vacantes",
    openings: {
      lead: { role: "Maestro titular de preescolar", campus: "Tucson o Yuma", req: "Autorización de huellas digitales, título universitario; se prefiere AEPA o NES." },
      assistant: { role: "Maestro asistente", campus: "Tucson o Yuma", req: "Gusto por los niños de tres a cinco años; la experiencia en el salón es un plus." },
      care: { role: "Encargado de cuidado antes y después de clases", campus: "Cualquiera de los dos centros", req: "Entrada a las 7:00 a. m. o cierre de 3:30 a 6:00 p. m. Puntual, cálido y certificado." },
    },
    applyTitle: "Postularse",
    thanks: "Gracias. Un director le responderá si hay una vacante que coincida.",
    received: "Recibimos su solicitud.",
    failed: "No pudimos enviar su solicitud de empleo. Por favor llame al {phone}.",
    fields: { name: "Nombre", email: "Correo electrónico", phone: "Teléfono", role: "Puesto", campus: "Centro", message: "Por qué le interesa este trabajo" },
    eitherCampus: "Cualquiera de los dos centros",
    sending: "Enviando…",
    submit: "Enviar solicitud",
  },
  contactPage: {
    eyebrow: "Contacto",
    title: "Hablemos",
    lede: "Llame, escriba o envíe un mensaje. Las oficinas contestan de 7:00 a. m. a 6:00 p. m. en días hábiles escolares.",
    thanks: "Gracias. Un director le responderá pronto.",
    sent: "Mensaje enviado. Le responderemos en breve.",
    failed: "No pudimos enviar su mensaje. Por favor llame al {phone}.",
    fields: { name: "Nombre", email: "Correo electrónico", topic: "Tema", message: "Mensaje" },
    topics: {
      general: "Pregunta general",
      tour: "Visita",
      enrollment: "Inscripción",
      des: "DES / colegiatura",
      current: "Familia inscrita",
    },
    sending: "Enviando…",
    submit: "Enviar mensaje",
  },
  owlivia: {
    name: "Owlivia",
    role: "Nuestra asistente: escriba o hable",
    open: "Pregúntele a Owlivia",
    greeting:
      "Hola, soy Owlivia. Pregúnteme lo que quiera sobre Capstone Quest: el programa, la colegiatura, DES o el día escolar. También puedo agendarle una visita al centro.",
    voiceHint: "También puede hablar conmigo en voz alta.",
    liveHint: "Está en línea: puede empezar a hablar.",
    startCall: "Llamar por voz",
    connecting: "Conectando…",
    endCall: "Terminar la llamada",
    callAgain: "Llamar de nuevo",
    tryAgain: "Intentar de nuevo",
    thinking: "Owlivia está escribiendo…",
    inputLabel: "Su mensaje para Owlivia",
    placeholder: "Escriba su pregunta…",
    send: "Enviar",
    youSaid: "Usted: ",
    noReply: "Disculpe, no entendí eso. ¿Podría decirlo de otra forma?",
    failed: "Disculpe, tengo problemas en este momento. Por favor llame al {phone}.",
    slow: "Disculpe, esto está tardando más de lo normal. Inténtelo otra vez o llame al {phone}.",
    disclaimer: "Owlivia es una asistente automatizada y puede equivocarse. Para algo importante, llame al",
  },

  tourPage: {
    eyebrow: "Visítenos",
    title: "Agende una visita",
    lede: "Recorra los salones, conozca a una maestra y vea una mañana real. Las visitas duran unos 30 minutos. Elija un centro y luego cualquier horario disponible.",
    pickCampus: "¿Qué centro le gustaría visitar?",
    helpTitle: "¿Prefiere hablar con alguien?",
    helpText: "Llame al centro y buscamos un horario con usted. Con gusto respondemos preguntas sobre el programa, la colegiatura o DES antes de su visita.",
    bookingNote: "Las reservaciones las maneja Cal.com y ese paso está en inglés. Llámenos si desea reservar en español.",
  },

  enrollPage: {
    eyebrow: "Inscripción",
    title: "Inscriba a su hijo",
    lede: "La inscripción se hace en papel. Descargue el paquete de inscripción, llénelo y entréguelo en la oficina de inscripciones de su centro.",
    download: "Descargar el paquete de inscripción",
    fileInfo: "PDF · {pages} páginas · {size}",
    languageNote: "El paquete está disponible solo en inglés.",
    stepsTitle: "Cómo inscribirse",
    steps: [
      "Descargue e imprima el paquete. Llene un paquete por cada niño.",
      "Llénelo y fírmelo donde se indica. El certificado de vacunas debe llenarlo el médico o la clínica de su hijo, o puede adjuntar una copia del registro oficial de vacunas firmado o sellado por el proveedor.",
      "Entregue el paquete completo en la oficina de inscripciones de su centro. Después recibirá una invitación para la aplicación ProCare para padres.",
    ],
    note: "Todos los niños deben tener un contrato firmado y los documentos de inscripción vigentes en la oficina antes de su primer día.",
    helpTitle: "¿Necesita ayuda o el paquete en otro formato?",
    help: "Si no puede imprimir el paquete, no puede usar un PDF o le gustaría ayuda para llenarlo, comuníquese con su centro. Podemos revisarlo con usted por teléfono o en persona, o dárselo en otro formato.",
    emailLabel: "Correo electrónico",
    campusLabel: "Centro {campus}",
  },
  accessibilityPage: {
    eyebrow: "Accesibilidad",
    title: "Declaración de accesibilidad",
    updated: "Revisada por última vez el 16 de septiembre de 2026",
    commitmentTitle: "Nuestro compromiso",
    commitment: [
      "En Capstone Quest Academy queremos que todas las familias puedan usar este sitio web, incluidos los padres y cuidadores que utilizan un lector de pantalla, navegan con el teclado, agrandan el texto o dependen de los subtítulos.",
      "La accesibilidad forma parte de este sitio desde su construcción; no se añadió después. Esto incluye un panel de accesibilidad que puede abrir desde la parte superior de cualquier página, con controles para el tamaño del texto, mayor contraste, enlaces subrayados, una tipografía más sencilla y movimiento reducido. Sus preferencias se guardan en su propio dispositivo y se aplican antes de que aparezca la página.",
    ],
    standardTitle: "La norma que seguimos",
    standard: "Nuestro objetivo es cumplir con las Pautas de Accesibilidad para el Contenido Web (WCAG) versión 2.2, nivel AA. Son las pautas reconocidas internacionalmente para que el contenido web sea utilizable por personas con discapacidad, y son la norma que más se aplica en los Estados Unidos.",
    standingTitle: "Situación actual",
    standing: [
      "Este sitio fue auditado conforme a las WCAG 2.2, nivel AA, el 16 de septiembre de 2026, y se volvió a probar después de las correcciones, mediante pruebas automatizadas y una revisión manual página por página.",
      "La auditoría concluyó que el sitio está en buenas condiciones. Identificó seis puntos de mejora; ninguno impedía encontrar nuestros programas, entender la colegiatura ni solicitar una visita. Las pruebas automatizadas ya no reportan ningún problema en ninguna página, en ninguno de los dos idiomas.",
      "El sitio cumple parcialmente con las WCAG 2.2, nivel AA: la mayor parte cumple con la norma, y las excepciones que conocemos se indican abajo.",
      "Auditaremos el sitio al menos una vez al año, y después de cualquier cambio importante.",
    ],
    improvingTitle: "En qué seguimos mejorando",
    improvingIntro: "Preferimos decírselo nosotros.",
    auditResult: "La auditoría del 16 de septiembre de 2026 identificó seis puntos. Al volver a probarlos, tres se corrigieron: el contenido que quedaba debajo del encabezado del sitio al recorrer una página o seguir un enlace, el botón de cambio de idioma que no estaba marcado como texto en otro idioma y la estructura de las regiones de la página de inicio. Dos ya funcionaban correctamente: la forma en que los lectores de pantalla anuncian el nombre de la escuela y el contorno de foco del teclado en los botones oscuros.",
    openIntro: "Queda abierto un punto de la auditoría, junto con otras cuatro limitaciones que conocemos:",
    open: [
      "Estamos revisando los colores de las letras de nuestro nombre en la página de inicio. Cumplen con el contraste exigido en el tamaño en que aparecen, pero con poco margen.",
      "El Manual para Padres en PDF aún no se ha revisado por completo en cuanto a accesibilidad. El manual también está publicado en este sitio como página web, y esa versión sí es accesible.",
      "Nuestro paquete de inscripción es un PDF escaneado, por lo que un lector de pantalla no puede leerlo y no se puede llenar en la pantalla. Si lo necesita en otro formato, o ayuda para llenarlo, comuníquese con su centro y lo revisaremos con usted por teléfono o en persona.",
      "La reservación de visitas en la página Agende una visita la proporciona Cal.com. Esa parte de la página la construyen ellos, no nosotros, y solo está en inglés. Si no le funciona, llame a su centro y agendamos la visita con usted.",
      "Algunos documentos de la página de Recursos para familias —el manual del estudiante, la política de bienestar, los menús y la lista de útiles— los publica AmeriSchools Academy, no nosotros, y es posible que no sean totalmente accesibles. Le daremos cualquiera de ellos en otro formato si lo solicita.",
    ],
    helpTitle: "Si algo no le funciona",
    helpIntro: "Por favor, díganoslo. No nos molesta en absoluto: nos ayuda a corregirlo para la siguiente familia.",
    emailLabel: "Correo electrónico",
    campusLabel: "Centro {campus}",
    hoursLabel: "Horario",
    helpDetails: "Indíquenos en qué página estaba y qué ocurrió. Procuramos responder en un plazo de dos días hábiles.",
    formats: "Si necesita información de este sitio en otro formato —letra grande, texto sencillo o leída por teléfono—, pídanosla y se la proporcionaremos.",
    technicalTitle: "Notas técnicas",
    technical: [
      "Esta declaración se aplica al sitio web capstonequestacademy.com, en inglés y en español.",
      "El sitio no utiliza un complemento de accesibilidad de terceros. Las funciones de accesibilidad están integradas en el propio sitio.",
      "Las tipografías se sirven desde nuestro propio sitio y no desde un tercero.",
      "Esta declaración se revisó por última vez el 16 de septiembre de 2026.",
    ],
  },

  privacyPage: {
    eyebrow: "Privacidad",
    title: "Aviso de privacidad",
    updated: "Última actualización: 16 de septiembre de 2026",
    lede: "Aquí le explicamos qué información recopila este sitio, para qué y quién la ve. Está escrito para que lo lea una familia, no un abogado.",
    summaryTitle: "En pocas palabras",
    summary: [
      "Lo único que recopilamos es lo que usted escribe en un formulario y nos envía.",
      "Este sitio no tiene publicidad, ni rastreo, ni cookies.",
      "Los formularios llegan por correo a las oficinas de la escuela y las visitas se agendan por medio de Cal.com. No vendemos ni compartimos su información.",
    ],
    sections: {
      who: {
        title: "Quiénes somos",
        body: "Capstone Quest Academy opera los programas preescolares de nuestros centros de Tucson y Yuma y es responsable de la información que se recopila en este sitio. Nuestros datos de contacto están al final de esta página.",
      },
      collect: {
        title: "Qué información recopilamos",
        intro: "Solo recopilamos información cuando usted decide enviárnosla por medio de alguno de los formularios del sitio. No se recoge nada en segundo plano.",
        tour: "Reservación de visitas: las visitas se agendan a través de Cal.com, un servicio de programación que actúa por cuenta nuestra. Cal.com le pide su nombre, correo electrónico y teléfono, y le envía una confirmación. Cal.com gestiona esa reservación por cuenta nuestra; nosotros vemos la cita en nuestro calendario.",
        contact: "Formulario de contacto: su nombre, su correo electrónico, el tema que elija y su mensaje.",
        careers: "Solicitud de empleo: su nombre, correo electrónico y teléfono, el puesto y el centro que solicita, y su mensaje.",
        note: "En ninguna parte de este sitio le pedimos número de Seguro Social, datos de pago ni información sobre su situación migratoria.",
      },
      why: {
        title: "Para qué la usamos",
        body: "Para responder su pregunta, agendar su visita o considerar su solicitud de empleo. No la usamos para enviarle publicidad ni lo agregamos a una lista de correos.",
      },
      recipients: {
        title: "Quién más la ve",
        body: "Cuando usted envía un formulario, el mensaje llega a los correos de la escuela por medio de Resend, un servicio de entrega de correo que actúa por cuenta nuestra. Ese servicio maneja el mensaje solo para entregarlo y no lo usa para sus propios fines. Nadie más recibe lo que usted envía.",
      },
      dont: {
        title: "Lo que este sitio no hace",
        items: [
          "Sin analíticas. No medimos ni registramos su visita.",
          "Sin publicidad ni píxeles de rastreo, y no se comparte nada con anunciantes ni redes sociales.",
          "Sin cookies. Este sitio no coloca ninguna.",
          "Nunca vendemos su información ni la compartimos para la mercadotecnia de terceros.",
        ],
      },
      browser: {
        title: "Lo que guarda su propio navegador",
        body: "Si cambia el idioma o usa el menú de accesibilidad, su preferencia se guarda en su propio dispositivo para que el sitio la recuerde la próxima vez. Esas dos preferencias nunca salen de su dispositivo y nunca se nos envían. Si borra los datos de su navegador, desaparecen.",
      },
      children: {
        title: "Información sobre los niños",
        body: "Las visitas las agenda un padre, madre o tutor. La inscripción se hace en papel: el paquete de inscripción se descarga de este sitio, pero se llena y se entrega en la oficina de inscripciones del centro, así que este sitio nunca lo recibe. No recopilamos información directamente de los niños a sabiendas, y este sitio no está dirigido a niños.",
      },
      retention: {
        title: "Cuánto tiempo la conservamos",
        body: "[PERIODO DE CONSERVACIÓN — POR CONFIRMAR] Las solicitudes de familias que no se inscriben, y las solicitudes de candidatos que no contratamos, se eliminan de nuestros correos después de ese periodo. Si su hijo se inscribe, sus datos se conservan como parte de su expediente escolar, que se describe más abajo.",
      },
      choices: {
        title: "Consultar, corregir o eliminar su información",
        body: "Puede pedirnos qué información tenemos sobre usted, pedirnos que la corrijamos o que la eliminemos. Comuníquese con nosotros con los datos de abajo y le responderemos. Preguntar no tiene ninguna consecuencia y no afecta el lugar de su hijo ni su solicitud de empleo.",
      },
      scope: {
        title: "Lo que este aviso no cubre",
        body: "Este aviso cubre únicamente este sitio web. Una vez que un niño se inscribe, su expediente escolar se maneja por separado, conforme a los documentos de inscripción y a los sistemas que la escuela usa con las familias. Este sitio también enlaza a otras organizaciones, como AmeriSchools, Clever, PowerSchool, ClassDojo, RAZ Kids, Khan Academy Kids y Quality First Arizona. Esos sitios tienen sus propios avisos de privacidad y no somos responsables de ellos.",
      },
      changes: {
        title: "Cambios a este aviso",
        body: "Si cambiamos la forma en que este sitio maneja la información, actualizaremos esta página y la fecha que aparece arriba.",
      },
      contact: {
        title: "Comuníquese con nosotros",
        body: "Llámenos, escríbanos o pase a la oficina de cualquiera de los dos centros. Preferimos responder su pregunta a que se quede con la duda.",
      },
    },
  },
  handbookPage: {
    eyebrow: "Manual para padres",
    title: "Manual para padres de Capstone Quest Academy",
    subtitle: "Programa de aprendizaje infantil · Preescolar · Programa de la mañana (antes) y de la tarde (después)",
    lede: "Todo lo que las familias necesitan saber sobre el programa preescolar, desde la admisión hasta el horario diario. La versión para imprimir está disponible en PDF.",
    downloadPdf: "Descargar el PDF",
    contentsTitle: "Contenido",
    officesTitle: "Oficinas escolares",
    officesNote: "Llame directamente al centro; la oficina contesta durante el horario del programa.",
    foreword: {
      title: "Presentación",
      p1: "Bienvenido a otro año emocionante educando a niños de preescolar, de 3 a 5 años, creando una visión para el aprendizaje en la primera infancia. Como padre o madre, usted nos confía su bien más preciado: un hijo amado.",
      p2: "El maestro y cada familia son parte importante del equipo de enseñanza y aprendizaje para el futuro del niño. Cada uno actúa como responsable de brindar un entorno seguro y de asegurar oportunidades que marcan toda una vida. Estas responsabilidades compartidas se vuelven metas clave para atender las necesidades de los niños y las familias.",
      p3: "El programa académico de preescolar es de cinco días a la semana, con un programa de llegada temprana (a. m.) o salida tardía (p. m.) que se ofrece como cuidado infantil con costo adicional. La llegada temprana (7:00–8:00 a. m.) y la salida tardía (3:30–6:00 p. m.) atienden las necesidades de supervisión y seguridad de los niños y las familias.",
      p4: "El programa de preescolar es un ambiente cálido, afectuoso y seguro que da una base sólida para el éxito escolar futuro. El niño pequeño aprende a resolver problemas en situaciones desafiantes. El salón es un excelente laboratorio que ayuda a definir y crear recursos para el crecimiento y la madurez. El objetivo final es fomentar el amor por el aprendizaje durante toda la vida.",
    },
    philosophy: {
      title: "Filosofía y programa",
      valuesTitle: "Lo que valoramos",
      values: [
        "Sin calificaciones por grado", "Instrucción personalizada", "Personal altamente capacitado",
        "Instrucción basada en habilidades", "Plan de estudios integrado", "Enriquecimiento",
        "La comunidad como laboratorio", "Altos estándares académicos", "Posibilidad de elegir",
      ],
      descriptionTitle: "Descripción del programa",
      description: "Capstone Quest Academy ofrece un programa preescolar de escuela privada para familias y niños de 3 a 5 años que aún no tienen edad para el kínder. Cada centro de aprendizaje se ubica dentro de un centro de la escuela chárter AmeriSchools Academy.",
      datesTitle: "Fechas y horario de servicio",
      dates: "El programa académico de preescolar es de cinco días a la semana. Capstone Quest se ofrece durante los recesos escolares si la participación lo permite, excepto en Año Nuevo, el Día de Martin Luther King, el Día de los Presidentes, el Día de los Caídos, el Día de la Independencia, el Día del Trabajo, el Día de la Raza, el Día de los Veteranos, el Día de Acción de Gracias y la Navidad. El programa de llegada temprana (a. m.) o salida tardía (p. m.) se ofrece como cuidado infantil con costo adicional donde el centro cuenta con licencia para ello.",
      curriculumTitle: "Plan de estudios",
      curriculum: "Este programa es un ambiente cálido, afectuoso y seguro que ofrece una experiencia apropiada para el desarrollo. El niño pequeño vive reglas de autocontrol y resuelve problemas en situaciones desafiantes, ya sea en la comunidad, la escuela o la familia. El salón es una comunidad de niños pequeños que empiezan a aceptar, o a rechazar razonablemente, las reglas de conducta. Esa experiencia ofrece límites claros y ayuda a crear recursos personales para el crecimiento y la madurez.",
      centersTitle: "Centros temáticos para el aprendizaje infantil",
      centers: [
        "Rutinas de cuidado diario", "Matemáticas y material manipulable", "Juego activo", "Ciencia y naturaleza",
        "Música y movimiento", "Juego con agua y arena", "Juego con bloques", "Experiencias creativas",
        "Juego dramático", "Nosotros, tú y yo",
      ],
      quote: "El juego es la forma favorita de aprender de nuestro cerebro",
      quoteAuthor: "Diane Ackerman",
      partnership: "Los planes de clase se publican a diario, conforme a los requisitos de licencia. Animamos a las familias a leerle a su hijo, recitar rimas infantiles, cantar canciones o jugar a “Veo, veo” en el coche. Esos momentos compartidos fortalecen los lazos familiares. Este laboratorio de aprendizaje valora el juego y el descanso, el ejercicio físico, la exploración del lenguaje previa a la lectura y el desarrollo de habilidades cognitivas y sociales.",
    },
    admissions: {
      title: "Admisiones al programa",
      criteriaTitle: "Criterios de admisión",
      criteriaIntro: "Hay un número limitado de lugares para niños de preescolar de 3 a 5 años que aún no tienen edad para el kínder. Se espera que los niños que participan en el programa puedan:",
      criteria: [
        "Seguir instrucciones sencillas del maestro",
        "Vestirse, comer e ir al baño por sí mismos",
        "Convivir de manera adecuada con los demás",
        "Pasar de una actividad a otra sin instrucciones repetidas",
        "Expresarse oralmente de forma adecuada para su edad",
      ],
      registrationTitle: "Inscripción del alumno",
      registrationIntro: "Toda familia debe completar la inscripción antes del primer día de su hijo. Esto incluye:",
      registration: [
        "El paquete de inscripción",
        "Cartilla de vacunación vigente",
        "Tarjeta de emergencia vigente",
        "Una copia del acta de nacimiento del niño",
        "Comprobante de domicilio",
      ],
      registrationNote: "Para cancelar una inscripción, avise a la oficina de registro dos semanas antes de la salida.",
      contractTitle: "Contrato de colegiatura",
      contract: "Las familias firman un contrato de colegiatura con pagos semanales, que vencen el primer día de cada semana a través del portal en línea ProCare. Al inscribirse se paga un depósito equivalente a una semana de colegiatura, que se acredita a la primera semana de asistencia del niño. La colegiatura semanal reserva el lugar del niño aunque falte. Si el pago no se recibe el primer día de la semana, el niño no puede asistir y el lugar puede ofrecerse a otra familia.",
      contractLink: "Ver las tarifas actuales en la página de colegiatura",
      collectionsTitle: "Cobranza",
      collections: "La participación en el programa requiere el pago de las cuotas vigentes. La participación es voluntaria; el pago es obligatorio. La colegiatura no pagada es una obligación contractual y puede enviarse a cobranza.",
      refundTitle: "Reembolsos",
      refund: "No se otorgan créditos ni reembolsos por ausencias.",
    },
    participation: {
      title: "Participación en el programa",
      arrival: {
        title: "Llegada",
        body: "Las familias son responsables de llevar a sus hijos a la escuela cada día. Al llegar, registre la entrada de su hijo en la aplicación ProCare o en la tableta disponible, y acompáñelo al salón o al área de reunión. Nunca deje a un niño sin supervisión si no hay personal presente. Dejar a un niño solo en la llegada temprana es ilegal según la ley estatal, y no seguir estas normas puede dar lugar a un reporte a Servicios de Protección Infantil.",
      },
      dismissal: {
        title: "Salida",
        body: "Las familias registran la salida en la aplicación ProCare o en la tableta y recogen a sus hijos a la hora de salida. El personal acompaña a los niños al área de entrega. Los niños se entregan únicamente a los padres o a los adultos autorizados en la hoja de contactos; un adulto autorizado que no sea el padre o la madre debe firmar la hoja de salida y mostrar identificación con foto. Por favor sea puntual. La recogida tardía cuesta $1.00 por minuto por niño. Si surge una emergencia, llame a la oficina de registro e indique a qué hora llegará.",
      },
      attendance: {
        title: "Asistencia",
        body: "Se espera asistencia regular y puntual, y las normas de licencia exigen registros de asistencia de cada niño. Una lista de espera por orden de llegada respalda la capacidad del programa.",
      },
      options: {
        title: "Opciones de horario",
        body: "El horario de preescolar ofrece dos opciones para cada familia.",
        items: [
          "Programa n.º 1: preescolar Capstone, de 8:00 a. m. a 3:30 p. m.",
          "Programa n.º 2: preescolar Capstone más el programa complementario de 7:00 a. m. a 6:00 p. m., de lunes a viernes. Sigue el calendario de primaria de AmeriSchools Academy, salvo que el preescolar ofrece sesión de verano con un receso de dos semanas y otros descansos.",
        ],
      },
      immunizations: {
        title: "Vacunas",
        body: "Como condición para la inscripción, la cartilla de vacunación de cada niño debe estar vigente. El registro debe llevar el sello del consultorio médico, y el nombre, la dirección y el teléfono de la clínica deben anotarse en la Tarjeta de Salud de Emergencia antes de que el niño asista.",
      },
      medication: {
        title: "Medicamentos",
        body: "Las familias deben informar a la escuela de cualquier condición médica, física o discapacitante que limite la participación de su hijo, incluidas alergias al clima, al polen, a alimentos o a medicamentos. El Formulario de Consentimiento para Medicamentos autoriza al personal a administrar medicamentos recetados durante el día. La oficina de registro guarda y administra los medicamentos, que deben estar en su envase original y etiquetado. Los niños no pueden portar ni tomar medicamentos por sí mismos.",
      },
      snack: {
        title: "Refrigerio",
        body: "El programa sigue las normas de servicio de alimentos y nutrición de la licencia para la primera infancia. El refrigerio de la tarde es en sí un centro de aprendizaje sobre alimentos y nutrición, y su costo está incluido en la cuota del programa. El Formulario de Alergias Alimentarias se llena al inscribirse para retirar esos alimentos de las opciones de refrigerio.",
      },
      backpacks: {
        title: "Mochilas",
        body: "Envíe una mochila lo bastante grande para una carpeta con el nombre de su hijo. En ella viajan a casa papeles, dibujos y recuerdos. Guardarla siempre en el mismo lugar ayuda al niño a hacerse responsable de sus cosas. Por favor revise la mochila y la carpeta todos los días.",
      },
      fireDrills: {
        title: "Simulacros de incendio",
        body: "Se realizan simulacros de evacuación sin aviso al menos cada 30 días, como exige la ley. Los planes de evacuación están publicados en cada salón.",
      },
      emergency: {
        title: "Disposiciones de emergencia",
        bodyIntro: "Los primeros auxilios los brinda el maestro del salón. Si un niño se enferma, un miembro del personal lo acompaña a la oficina y se avisa a un padre o adulto responsable. La atención de emergencia depende de que la Tarjeta de Salud de Emergencia esté al día, y debe incluir:",
        items: [
          "Domicilio actual y teléfono fijo o celular",
          "Lugar de trabajo y teléfonos de todos los adultos responsables",
          "Nombres de cuatro adultos responsables además del padre o la madre",
        ],
        bodyEnd: "Los niños con enfermedades contagiosas, incluidos fiebre, diarrea, vómito u otra condición incapacitante, deben quedarse en casa. La familia es responsable de reportar la ausencia y la condición de salud. Las cuotas no se reducen por ausencia.",
      },
      conferences: {
        title: "Conferencias con las familias",
        body: "Las conferencias formales se realizan cada seis semanas para hablar del avance académico y del desarrollo de cada niño. La primera conferencia es en persona. También hay conferencias informales por teléfono y mensaje. Por favor organice por su cuenta la supervisión después de clases cuando el horario de salida lo requiera.",
      },
      discipline: {
        title: "Disciplina",
        body: "El juego es una poderosa actividad de enseñanza. Enseñar disciplina por medio del juego se centra en que el niño experimente conductas eficaces, empezando por los adultos que modelan actos con propósito. Las estrategias incluyen mostrar habilidades adecuadas para afrontar situaciones, preparar actividades apropiadas para el desarrollo y ordenadas según la madurez del niño, programar actividades en un entorno controlado y ofrecer reglas de conducta claras, consistentes y justas.",
      },
      pesticide: {
        title: "Aplicación de plaguicidas",
        body: "Se informa a las familias, los alumnos y el personal cuando se aplican plaguicidas en la propiedad escolar, actualmente con al menos 48 horas de anticipación, como exige la ley estatal. El aviso incluye notificación oral a alumnos y personal, aviso por escrito a los padres o tutores, y letreros que señalan las áreas de aplicación. Cada centro conserva registros escritos de estos avisos. Esto no incluye desinfectantes, sanitizantes ni desodorantes de uso no restringido.",
      },
    },
    suspension: {
      title: "Política de prevención de suspensión y expulsión",
      commitmentTitle: "Nuestro compromiso",
      commitment: "Creemos que todo niño merece sentirse seguro, apoyado y bienvenido en su entorno de aprendizaje temprano. Los niños pequeños aún están desarrollando habilidades sociales, emocionales y de conducta, y el comportamiento es una forma de comunicación. Nos comprometemos a prevenir la suspensión y la expulsión siempre que sea posible, mediante enseñanza proactiva, relaciones sólidas con las familias y colaboración con socios comunitarios. La salida del programa se considera solo como último recurso, después de haber agotado las estrategias y los recursos de apoyo. Esta política sigue la Política de Prevención de Suspensión y Expulsión del Departamento de Seguridad Económica de Arizona.",
      preventionTitle: "Prevención e intervención temprana",
      prevention: [
        "Mantener rutinas diarias predecibles y salones acogedores",
        "Enseñar habilidades socioemocionales con modelado y práctica guiada",
        "Usar orientación positiva de la conducta y redirección",
        "Ajustar el entorno del salón o las expectativas a las necesidades de cada niño",
        "Apoyar al personal con acompañamiento, supervisión reflexiva y formación profesional",
      ],
      familyTitle: "Alianza y comunicación con la familia",
      familyIntro: "Las familias son aliadas valiosas. Cuando se identifica una preocupación de conducta o desarrollo, haremos lo siguiente:",
      family: [
        "Compartir observaciones con la familia desde las fortalezas del niño",
        "Invitar a la familia a participar en la búsqueda de soluciones",
        "Desarrollar juntos estrategias de apoyo o planes individualizados",
        "Tomar en cuenta las perspectivas culturales, lingüísticas y familiares al planear los apoyos",
      ],
      inclusionTitle: "Inclusión y apoyo para todos los niños",
      inclusionIntro: "No negamos la inscripción ni damos de baja a un niño por un retraso del desarrollo, una discapacidad, un reto de conducta o una posible necesidad especial sin antes poner en marcha intervenciones de apoyo. Los apoyos pueden incluir:",
      inclusion: [
        "Planes individualizados de conducta o de apoyo",
        "Modificaciones del entorno o del horario",
        "Apoyo adicional en el salón",
        "Evaluaciones del desarrollo con el consentimiento de la familia",
        "Colaboración con servicios de intervención temprana o educación especial",
      ],
      consultationTitle: "Consulta y recursos comunitarios",
      consultationIntro: "Antes de considerar una suspensión o expulsión, buscamos apoyos adicionales cuando están disponibles:",
      consultation: [
        "Referencia a AZ STEPS, el programa estatal de Arizona de capacitación y asistencia técnica para la prevención de expulsiones",
        "Consulta de salud mental en la primera infancia",
        "Especialistas en inclusión o consultores de conducta",
        "Servicios comunitarios de desarrollo o de apoyo familiar",
      ],
      documentationTitle: "Documentación y revisión",
      documentationIntro: "Documentamos las preocupaciones observadas, las estrategias aplicadas, la comunicación con la familia, los apoyos solicitados o recibidos y el avance a lo largo del tiempo. Las estrategias se revisan con regularidad y se ajustan.",
      lastResortTitle: "La suspensión o expulsión como último recurso",
      lastResortIntro: "La suspensión o expulsión se considera únicamente cuando se cumple todo lo siguiente:",
      lastResort: [
        "Existe un riesgo de seguridad grave y continuo",
        "Se han intentado adaptaciones e intervenciones razonables",
        "Se ha solicitado consulta o apoyo externo cuando estaba disponible",
      ],
      transitionIntro: "Si un niño debe dejar el programa, haremos lo siguiente:",
      transition: [
        "Avisar por escrito a la familia al menos cinco días hábiles antes de la baja",
        "Trabajar con la familia para encontrar cuidado o servicios alternativos",
        "Ofrecer referencias a recursos comunitarios",
        "Apoyar una transición respetuosa y planeada para reducir la afectación",
      ],
      reviewTitle: "Comunicación y revisión de la política",
      reviewIntro: "Esta política se comparte con las familias al inscribirse, se incluye en el manual, se revisa cada año con el personal y se actualiza conforme evolucionan las guías y las mejores prácticas.",
    },
    scheduleTitle: "Horario modelo de actividades diarias",
    scheduleNote: "Sujeto a cambios. Las puertas abren a las 7:00 a. m. para el programa de la mañana y a las 8:00 a. m. para el día completo.",
    napNote: "El programa proporciona a cada niño un tapete para la hora de la siesta.",
    recessNote: "El recreo al aire libre depende del clima, respetando el calor extremo.",
  },
};
