/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CampusesRouteImport } from './routes/campuses'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CleverRouteImport } from './routes/clever'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as InfoRouteImport } from './routes/info'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as TourRouteImport } from './routes/tour'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as CampusesIndexRouteImport } from './routes/campuses.index'
import { Route as CampusesSlugRouteImport } from './routes/campuses.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesRoute = CampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CleverRoute = CleverRouteImport.update({
  id: '/clever',
  path: '/clever',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesIndexRoute = CampusesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusesRoute,
} as any)
const CampusesSlugRoute = CampusesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CampusesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campuses': typeof CampusesRouteWithChildren
  '/careers': typeof CareersRoute
  '/clever': typeof CleverRoute
  '/contact': typeof ContactRoute
  '/enroll': typeof EnrollRoute
  '/info': typeof InfoRoute
  '/parents': typeof ParentsRoute
  '/portal': typeof PortalRoute
  '/programs': typeof ProgramsRoute
  '/tour': typeof TourRoute
  '/why-us': typeof WhyUsRoute
  '/campuses/$slug': typeof CampusesSlugRoute
  '/campuses/': typeof CampusesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clever': typeof CleverRoute
  '/contact': typeof ContactRoute
  '/enroll': typeof EnrollRoute
  '/info': typeof InfoRoute
  '/parents': typeof ParentsRoute
  '/portal': typeof PortalRoute
  '/programs': typeof ProgramsRoute
  '/tour': typeof TourRoute
  '/why-us': typeof WhyUsRoute
  '/campuses/$slug': typeof CampusesSlugRoute
  '/campuses': typeof CampusesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campuses': typeof CampusesRouteWithChildren
  '/careers': typeof CareersRoute
  '/clever': typeof CleverRoute
  '/contact': typeof ContactRoute
  '/enroll': typeof EnrollRoute
  '/info': typeof InfoRoute
  '/parents': typeof ParentsRoute
  '/portal': typeof PortalRoute
  '/programs': typeof ProgramsRoute
  '/tour': typeof TourRoute
  '/why-us': typeof WhyUsRoute
  '/campuses/$slug': typeof CampusesSlugRoute
  '/campuses/': typeof CampusesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/campuses'
    | '/careers'
    | '/clever'
    | '/contact'
    | '/enroll'
    | '/info'
    | '/parents'
    | '/portal'
    | '/programs'
    | '/tour'
    | '/why-us'
    | '/campuses/$slug'
    | '/campuses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/clever'
    | '/contact'
    | '/enroll'
    | '/info'
    | '/parents'
    | '/portal'
    | '/programs'
    | '/tour'
    | '/why-us'
    | '/campuses/$slug'
    | '/campuses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/campuses'
    | '/careers'
    | '/clever'
    | '/contact'
    | '/enroll'
    | '/info'
    | '/parents'
    | '/portal'
    | '/programs'
    | '/tour'
    | '/why-us'
    | '/campuses/$slug'
    | '/campuses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CampusesRoute: typeof CampusesRouteWithChildren
  CareersRoute: typeof CareersRoute
  CleverRoute: typeof CleverRoute
  ContactRoute: typeof ContactRoute
  EnrollRoute: typeof EnrollRoute
  InfoRoute: typeof InfoRoute
  ParentsRoute: typeof ParentsRoute
  PortalRoute: typeof PortalRoute
  ProgramsRoute: typeof ProgramsRoute
  TourRoute: typeof TourRoute
  WhyUsRoute: typeof WhyUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses': {
      id: '/campuses'
      path: '/campuses'
      fullPath: '/campuses'
      preLoaderRoute: typeof CampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clever': {
      id: '/clever'
      path: '/clever'
      fullPath: '/clever'
      preLoaderRoute: typeof CleverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses/': {
      id: '/campuses/'
      path: '/'
      fullPath: '/campuses/'
      preLoaderRoute: typeof CampusesIndexRouteImport
      parentRoute: typeof CampusesRoute
    }
    '/campuses/$slug': {
      id: '/campuses/$slug'
      path: '/$slug'
      fullPath: '/campuses/$slug'
      preLoaderRoute: typeof CampusesSlugRouteImport
      parentRoute: typeof CampusesRoute
    }
  }
}

interface CampusesRouteChildren {
  CampusesSlugRoute: typeof CampusesSlugRoute
  CampusesIndexRoute: typeof CampusesIndexRoute
}

const CampusesRouteChildren: CampusesRouteChildren = {
  CampusesSlugRoute: CampusesSlugRoute,
  CampusesIndexRoute: CampusesIndexRoute,
}

const CampusesRouteWithChildren = CampusesRoute._addFileChildren(
  CampusesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CampusesRoute: CampusesRouteWithChildren,
  CareersRoute: CareersRoute,
  CleverRoute: CleverRoute,
  ContactRoute: ContactRoute,
  EnrollRoute: EnrollRoute,
  InfoRoute: InfoRoute,
  ParentsRoute: ParentsRoute,
  PortalRoute: PortalRoute,
  ProgramsRoute: ProgramsRoute,
  TourRoute: TourRoute,
  WhyUsRoute: WhyUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
